### ISSUE TITLE
What files have the relevant changes for the Asset Manager prototype?

### ISSUE THREAD

**Issue by Draise14** [CreativeDesigner3D/BlenderSource#1]
I'm gonna compile this soon, but before I do, I wanted to review the files that had the relevant code for the asset manager. Which files are they? 

I assume not everything is in Python, so will have to be reviewed before compilation. Any hints how you built this?

**Comment by CreativeDesigner3D** [comment]
I made very few changes to Blenders Source. You can see all of the files modified in this commit. 

https://github.com/CreativeDesigner3D/BlenderSource/commit/6a0bebe5c4fde4ddac41021e49deaca63c3501be

Also you can build this just like you build a regular version of Blender. 

https://wiki.blender.org/wiki/Building_Blender

**Comment by Draise14** [comment]
This is the relevant file browser changes that make it more like an asset manager as per this build:
`bp_filebrowser_ui.py`

**Comment by CreativeDesigner3D** [comment]
That's where the UI changes are. The drag and drop operator is in bp_window_manager.py

**Comment by CreativeDesigner3D** [comment]
I will be releasing more information on this soon.
