### ISSUE TITLE
Console Error on Compilation

### ISSUE THREAD

**Issue by Draise14** [CreativeDesigner3D/BlenderSource#2]
Ok, did a fresh build. A module in missing. I've attached the code below. I also could not find the asset manager in the code. Is it the io_mesh or io_utils python script? 

It's looking for this: **io_scene_gltf2**

> found bundled python: H:\bforartists-repository\CreativeDesigner3D - Asset Manager-build\bin\Release\2.83\python
> Traceback (most recent call last):
>   File "H:\bforartists-repository\CreativeDesigner3D - Asset Manager-build\bin\Release\2.83\scripts\modules\addon_utils.py", line 351, in enable
>     mod = __import__(module_name)
>   File "H:\bforartists-repository\CreativeDesigner3D - Asset Manager-build\bin\Release\2.83\scripts\addons\io_anim_bvh\__init__.py", line 49, in <module>
>     from bpy_extras.io_utils import (
> ImportError: cannot import name 'orientation_helper_factory' from 'bpy_extras.io_utils' (H:\bforartists-repository\CreativeDesigner3D - Asset Manager-build\bin\Release\2.83\scripts\modules\bpy_extras\io_utils.py)
> Traceback (most recent call last):
>   File "H:\bforartists-repository\CreativeDesigner3D - Asset Manager-build\bin\Release\2.83\scripts\modules\addon_utils.py", line 351, in enable
>     mod = __import__(module_name)
>   File "H:\bforartists-repository\CreativeDesigner3D - Asset Manager-build\bin\Release\2.83\scripts\addons\io_mesh_ply\__init__.py", line 56, in <module>
>     from bpy_extras.io_utils import (
> ImportError: cannot import name 'orientation_helper_factory' from 'bpy_extras.io_utils' (H:\bforartists-repository\CreativeDesigner3D - Asset Manager-build\bin\Release\2.83\scripts\modules\bpy_extras\io_utils.py)
> Traceback (most recent call last):
>   File "H:\bforartists-repository\CreativeDesigner3D - Asset Manager-build\bin\Release\2.83\scripts\modules\addon_utils.py", line 351, in enable
>     mod = __import__(module_name)
>   File "H:\bforartists-repository\CreativeDesigner3D - Asset Manager-build\bin\Release\2.83\scripts\addons\io_mesh_stl\__init__.py", line 67, in <module>
>     from bpy_extras.io_utils import (
> ImportError: cannot import name 'orientation_helper_factory' from 'bpy_extras.io_utils' (H:\bforartists-repository\CreativeDesigner3D - Asset Manager-build\bin\Release\2.83\scripts\modules\bpy_extras\io_utils.py)
> Traceback (most recent call last):
>   File "H:\bforartists-repository\CreativeDesigner3D - Asset Manager-build\bin\Release\2.83\scripts\modules\addon_utils.py", line 351, in enable
>     mod = __import__(module_name)
>   File "H:\bforartists-repository\CreativeDesigner3D - Asset Manager-build\bin\Release\2.83\scripts\addons\io_scene_fbx\__init__.py", line 52, in <module>
>     from bpy_extras.io_utils import (
> ImportError: cannot import name 'orientation_helper_factory' from 'bpy_extras.io_utils' (H:\bforartists-repository\CreativeDesigner3D - Asset Manager-build\bin\Release\2.83\scripts\modules\bpy_extras\io_utils.py)
> Traceback (most recent call last):
>   File "H:\bforartists-repository\CreativeDesigner3D - Asset Manager-build\bin\Release\2.83\scripts\modules\addon_utils.py", line 351, in enable
>     mod = __import__(module_name)
> ModuleNotFoundError: No module named 'io_scene_gltf2'
> Traceback (most recent call last):
>   File "H:\bforartists-repository\CreativeDesigner3D - Asset Manager-build\bin\Release\2.83\scripts\modules\addon_utils.py", line 351, in enable
>     mod = __import__(module_name)
>   File "H:\bforartists-repository\CreativeDesigner3D - Asset Manager-build\bin\Release\2.83\scripts\addons\io_scene_obj\__init__.py", line 48, in <module>
>     from bpy_extras.io_utils import (
> ImportError: cannot import name 'orientation_helper_factory' from 'bpy_extras.io_utils' (H:\bforartists-repository\CreativeDesigner3D - Asset Manager-build\bin\Release\2.83\scripts\modules\bpy_extras\io_utils.py)
> Traceback (most recent call last):
>   File "H:\bforartists-repository\CreativeDesigner3D - Asset Manager-build\bin\Release\2.83\scripts\modules\addon_utils.py", line 351, in enable
>     mod = __import__(module_name)
>   File "H:\bforartists-repository\CreativeDesigner3D - Asset Manager-build\bin\Release\2.83\scripts\addons\io_scene_x3d\__init__.py", line 48, in <module>
>     from bpy_extras.io_utils import (
> ImportError: cannot import name 'orientation_helper_factory' from 'bpy_extras.io_utils' (H:\bforartists-repository\CreativeDesigner3D - Asset Manager-build\bin\Release\2.83\scripts\modules\bpy_extras\io_utils.py)

**Comment by Draise14** [comment]
![blender_2020-03-24_14-27-14](https://user-images.githubusercontent.com/35357409/77468503-a57e3a80-6ddb-11ea-81a7-add92e3c72d2.png)

Yeah, something is definitely missing. This may be the entire asset library prototype that you have. I have pulled the latest from here, but that file doesn't exist. 

Compilation has no errors.

**Comment by Draise14** [comment]
Ok, installed Prosidebar, still have the same issues, plus a couple otherswarnings: 

> Warning: 'Assembly_PT_library_settings' doesn't have upper case alpha-numeric prefix

**Comment by CreativeDesigner3D** [comment]
Thanks for the information. I will release some more information on how to enable and work with the add-ons.

**Comment by Draise14** [comment]
Got it. I copied the addons from the 2.82a official build of Blender and it's ok now. I still get the alpha-numeric prefix error. 

But now I can see what you've done. I see the `bp_filebrowser_ui.py` is where most of the modifications are now.
