### ISSUE TITLE
Blender 2.9

### ISSUE THREAD

**Issue by zeusent** [CreativeDesigner3D/BlenderSource#5]
Hi!

I wanted to give Home Builder a go. I see that I need to custom compile Blender for Mac based on the info found here https://creativedesigner3d.com/pyclone/ 

In the URL above you mention that Blender 2.9 is needed but it looks like this repo is a couple of months old and based on the commits messages Blender 2.83LTS is used. Is it missing some commits, or can I safely go ahead and compile the contents of this repo to use with Home Builder?

**Comment by fire** [comment]
I want to look at this. Currently fighting git trying to checkout blender LTS and blender 2.9.

**Comment by fire** [comment]
I made the code changes here, but haven't compiled it yet. https://github.com/fire/blender-1/tree/asset-library-2.91

Following instructions here: https://wiki.blender.org/wiki/Building_Blender/Windows

Had some submodule problems.

**Comment by fire** [comment]
https://github.com/fire/blender-1/releases/tag/v2.90.1-asset-library-pre-1

**Comment by CreativeDesigner3D** [comment]
I have just updated the source code in this repository. So now you can compile with the new version. Let me know if you have any issues.
